### ISSUE TITLE
Convergence not fast

### ISSUE THREAD

**Issue by blythed** [code-terminator/DilatedRNN#3]
Hi code-terminator, 

I cloned the repo and executed the example notebook.

However, convergence is not nearly as fast as figure 4 of your paper:

https://github.com/code-terminator/DilatedRNN.git

would suggest.

I used all of the default parameters.
<img width="572" alt="screen shot 2018-03-10 at 12 11 41" src="https://user-images.githubusercontent.com/15139331/37241606-341f86fc-245c-11e8-8331-691fea048a41.png">

In addition, shouldn't the notebook example be easier than the example in the paper?

**Comment by code-terminator** [comment]
Figure 4 in the paper is a different setup as the one in the repo (figure 4 is the "noisy" setting).  If you directly run the demo file, you are running the "permuted" setting in table 1.   Empirically, I also found that the noisy setting converges faster than the permuted one.
